# Generated by Django 4.1.3 on 2022-12-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=50)),
                ("common_address", models.CharField(max_length=100)),
                ("place_address", models.CharField(max_length=100)),
                ("place_breaktime", models.DateTimeField()),
                ("place_category", models.CharField(max_length=50)),
                ("place_number", models.IntegerField()),
                ("rating_sum", models.IntegerField()),
                ("rating_cnt", models.IntegerField()),
                ("place_img", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "db_place",
            },
        ),
    ]
