# Generated by Django 4.1.3 on 2022-12-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="place",
            table="place",
        ),
    ]
