# Generated by Django 4.1.3 on 2022-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="hit",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
