# Generated by Django 4.1.3 on 2022-12-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_category',
        ),
    ]
