# Generated by Django 4.1.3 on 2022-12-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.CharField(max_length=50, null=True, verbose_name="위도"),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.CharField(max_length=50, null=True, verbose_name="경도"),
        ),
    ]
