# Generated by Django 4.1.3 on 2022-12-03 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_remove_place_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_place', to=settings.AUTH_USER_MODEL, verbose_name='장소 북마크'),
        ),
    ]
