# Generated by Django 4.1.3 on 2022-12-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_place_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='place',
            name='munu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='메뉴'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_number',
            field=models.CharField(max_length=20, verbose_name='장소 전화번호'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_time',
            field=models.CharField(max_length=30, verbose_name='영업 시간'),
        ),
    ]
