# Generated by Django 4.1.3 on 2022-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='계정 생성일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_password_changed',
            field=models.DateTimeField(auto_now=True, verbose_name='비밀번호 마지막 변경일'),
        ),
    ]
