# Generated by Django 4.1.3 on 2022-12-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('욕설이 들어갔어요.', '욕설이 들어갔어요.'), ('성적인 발언이 들어갔어요.', '성적인 발언이 들어갔어요.'), ('정치적 요소가 들어갔어요.', '정치적 요소가 들어갔어요.'), ('관계 없는 내용이예요.', '관계 없는 내용이예요.'), ('도배된 내용이예요.', '도배된 내용이예요.'), ('광고성이 포함된 글이예요.', '광고성이 포함된 글이예요.'), ('기타', '기타')], max_length=30, verbose_name='신고 카테고리'),
        ),
    ]
