# Generated by Django 4.1.3 on 2022-12-09 02:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_review', to='places.place', verbose_name='장소'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image_one',
            field=models.ImageField(blank=True, upload_to='review_pics', validators=[django.core.validators.validate_image_file_extension], verbose_name='이미지 1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image_three',
            field=models.ImageField(blank=True, upload_to='review_pics', validators=[django.core.validators.validate_image_file_extension], verbose_name='이미지 3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image_two',
            field=models.ImageField(blank=True, upload_to='review_pics', validators=[django.core.validators.validate_image_file_extension], verbose_name='이미지 2'),
        ),
    ]
