# Generated by Django 4.1.3 on 2022-12-04 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('욕설이 들어갔어요.', '욕설이 들어갔어요.'), ('성적인 발언이 들어갔어요', '성적인 발언이 들어갔어요.'), ('정치적 요소가 들어갔어요', '정치적 요소가 들어갔어요.'), ('관계 없는 내용이예요.', '관계 없는 내용이예요.'), ('도배된 내용이예요.', '도배된 내용이예요.'), ('광고성이 포함된 글이예요', '광고성이 포함된 글이예요'), ('기타', '기타')], max_length=30, verbose_name='신고 카테고리')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='신고 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.comment', verbose_name='댓글')),
                ('recomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.recomment', verbose_name='대댓글')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='후기')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['created_at'],
            },
        ),
    ]
