# Generated by Django 4.1.3 on 2022-12-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(max_length=500, verbose_name='신고 내용'),
        ),
    ]
