# Generated by Django 4.1.3 on 2022-12-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_created_at_alter_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 16, 43, 56, 581755), verbose_name='후기 생성 시간'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 16, 43, 56, 581774), verbose_name='후기 수정 시간'),
        ),
    ]
